experiment_name: "IsoGrowingNCA_Chameleon_Coords"
task: "growing_2d"
device: "cuda:0"
precision: "float16"

nca:
  type: "IsoGrowingNCA"
  graft_initialization: null
  output_type: "s"

  nca_kwargs:
    channels: 32
    fc_dim: 256
    update_prob: 0.5

siren:
  hidden_features: 64
  hidden_layers: 2
  outermost_linear: True
  fx: "linear"
  activation: "sin"
  num_frequencies: 1
  first_omega_0: 10.0
  hidden_omega_0: 10.0
  disable: False
  disable_coords: False

train:
  epochs: 4000
  batch_size: 8
  lr: 0.001
  lr_decay_steps: [ 1000, 2000, 3000 ]
  lr_decay_gamma: 0.3
  num_repetitions: 5

  pool_size: 1024
  inject_seed_interval: 32
  step_range: [ 32, 96 ]

  summary_interval: 250

renderer:
  scale_factor: 8
  padding: "circular"
  fs_shader: "vanilla"

loss:
  overflow_loss_weight: 100.0
  image_loss_weight: 1.0

  image_loss_kwargs:
    target_path: "data/morphology_png/chameleon.png"
    image_size: [ 512, 512 ]
    padding: [ 128, 128 ]
    l2_weight: 1.0
    l1_weight: 1.0
    lpips_weight: 1.0
    premultiply_alpha: True

logger:
  backend: local
